openapi: 3.0.0
info:
  title: Orchestrator Service API
  version: 1.0.0
  description: API for orchestrating the order workflow.
servers:
  - url: http://localhost:3003
    description: Local Orchestrator Service
paths:
  /:
    get:
      summary: Get service status
      responses:
        '200':
          description: Orchestrator Service API is running.
  /place-order:
    post:
      summary: Initiate an order workflow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Unique identifier for the order.
                item:
                  type: string
                  description: Name of the item ordered.
                quantity:
                  type: integer
                  description: Quantity of the item.
                customerName:
                  type: string
                  description: Name of the customer.
                shippingAddress:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    zipCode:
                      type: string
                  required:
                    - street
                    - city
                    - zipCode
              required:
                - id
                - item
                - quantity
                - customerName
                - shippingAddress
      responses:
        '200':
          description: Order initiation request sent to orchestrator.
        '500':
          description: Orchestrator failed to connect to RabbitMQ.
  /workflow-status/{orderId}:
    get:
      summary: Get complete workflow status for an order
      parameters:
        - in: path
          name: orderId
          schema:
            type: string
          required: true
          description: The ID of the order to retrieve the workflow status for.
      responses:
        '200':
          description: Aggregated workflow status including order, payment, and shipping details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStatus'
        '500':
          description: Internal Server Error.
  /bpel/workflows:
    get:
      summary: List available BPEL workflows
      responses:
        '200':
          description: List of available BPEL workflows
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  workflows:
                    type: array
                    items:
                      type: string
  /bpel/workflows/{name}:
    get:
      summary: Get BPEL workflow definition
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: The name of the workflow to retrieve
      responses:
        '200':
          description: BPEL workflow definition
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  workflow:
                    $ref: '#/components/schemas/BPELWorkflow'
        '404':
          description: Workflow not found
  /bpel/workflows/{name}/execute:
    post:
      summary: Execute BPEL workflow
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: The name of the workflow to execute
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                item:
                  type: string
                quantity:
                  type: integer
                customerName:
                  type: string
                shippingAddress:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    zipCode:
                      type: string
      responses:
        '200':
          description: BPEL workflow execution completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  result:
                    $ref: '#/components/schemas/BPELExecutionResult'
        '500':
          description: Workflow execution failed
  /bpel/executions:
    get:
      summary: List BPEL workflow executions
      responses:
        '200':
          description: List of BPEL workflow executions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  executions:
                    type: array
                    items:
                      $ref: '#/components/schemas/BPELExecution'
  /bpel/executions/{id}:
    get:
      summary: Get BPEL execution status
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The execution ID to retrieve
      responses:
        '200':
          description: BPEL execution status
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  execution:
                    $ref: '#/components/schemas/BPELExecution'
        '404':
          description: Execution not found
components:
  schemas:
    OrderSummary:
      type: object
      properties:
        id:
          type: string
        item:
          type: string
        quantity:
          type: integer
        customerName:
          type: string
        shippingAddress:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            zipCode:
              type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    PaymentSummary:
      type: object
      properties:
        orderId:
          type: string
        paymentId:
          type: string
        amount:
          type: number
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ShippingSummary:
      type: object
      properties:
        orderId:
          type: string
        shippingId:
          type: string
        address:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            zipCode:
              type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    WorkflowStatus:
      type: object
      properties:
        orderId:
          type: string
          description: The ID of the order.
        details:
          type: object
          properties:
            order:
              $ref: '#/components/schemas/OrderSummary'
            payment:
              $ref: '#/components/schemas/PaymentSummary'
            shipping:
              $ref: '#/components/schemas/ShippingSummary'
    BPELWorkflow:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        description:
          type: string
        variables:
          type: object
        activities:
          type: array
          items:
            type: object
    BPELExecution:
      type: object
      properties:
        id:
          type: string
        workflowName:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        status:
          type: string
          enum: [running, completed, failed]
        currentActivity:
          type: integer
        variables:
          type: object
        inputData:
          type: object
        outputData:
          type: object
        error:
          type: string
        duration:
          type: integer
    BPELExecutionResult:
      type: object
      properties:
        executionId:
          type: string
        status:
          type: string
          enum: [completed, failed]
        result:
          type: object
        error:
          type: string
        duration:
          type: integer
